### ISSUE TITLE
Error when opening Quests with L and selecting on a quest

### ISSUE THREAD

**Issue by Rootkit-** [IrcDirk/Carbonite-Classic#100] opened 2019-11-09 15:08 UTC
When opening Quests with L and selecting on a quest 
```
Date: 2019-11-09 09:06:52
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 8375:
   attempt to index local 'quest' (a nil value)
Debug:
   [C]: ?
   Carbonite.Quests\NxQuest.lua:8375: func()
   ...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57:
      ...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vv1.9.17-classic
  AdiBagsPT3Filter, vv1.4.4-classic
  Atlas, vv1.45.01.11302
  AtlasBattlegrounds, vv1.45.00.11302.00
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasTransportation, vv1.45.00.11302.00
  AtlasLootClassic, vv1.3.3
  AtlasLootClassicData, vv1.3.3
  AtlasLootClassicDungeonsAndRaids, vv1.3.3
  AtlasLootClassicMaps, vv1.0.0
  AtlasQuest, v4.11.57
  Auctionator, v8.1.0
  Bartender4, v4.8.8
  BasicMinimap, vv1-classic
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  Buffet, v
  Carbonite, v@project-version@
  CarboniteQuests, v@project-version@
  CarboniteWarehouse, v@project-version@
  CEPGP, v
  ClassicAutoQuest, v1.5.1
  ClassicCastbars, vv1.1.4
  ClassicCastbarsOptions, v
  ClassicLFG, v1.1.3
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.5
  DejaClassicStats, v1302r037
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  FieldGuide, vv1.5-release
  FriendsInfo, v11302.9
  GatherMate2, v1.45.5
  GSE, v2.4.23
  GSEGUI, v2.4.23
  GSELDB, v2.4.23
  HandyNotes, vv1.5.9
  HandyNotesDungeonLocationsClassic, v1.03
  HandyNotesFlightMastersClassic, v1.06
  HandyNotesNPCsClassic, v1.21
  HideRaidManager, v1.0.1
  Immersion, v1.2.2
  InFlightLoad, v1.13.003
  ItemTooltipProfessionIcons, v1.1.3
  KillTrack, vv1.13.0
  LeatrixMaps, v1.13.36
  LeatrixPlus, v1.13.37
  LeatrixTunes, v1.13.09
  LightHeaded, vv11302-1.0.0
  LightHeadedDataA, vwowi:revision
  LightHeadedDataC, vwowi:revision
  LightHeadedDataD, vwowi:revision
  LightHeadedDataQIDNames, vwowi:revision
  MageButtons, v1.01
  MikScrollingBattleText, v5.7.149
  MissingTradeSkillsList, v1.13.24
  MoreStopwatches, vv1.15c
  OmniCC, v8.2.5
  Prat30, v3.7.36
  Prat30Libraries, v
  Quartz, v3.5.1
  Questie, v5.1.0
  RealMobHealth, v2.13
  Recount, vv1.13.2e
  RingMenu, v2.2.1
  SaySapped, v2019-08-27
  SkilletClassic, v1.04
  SpeedyAutoLoot, v2.0.25
  Spy, v1.0.13
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.2.6
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.1.3.11302
  TitanClassicAmmo, v1.1.3.11302
  TitanClassicBag, v1.1.3.11302
  TitanClassicClock, v1.1.3.11302
  TitanClassicGold, v1.1.3.11302
  TitanClassicLocation, v1.1.3.11302
  TitanClassicLootType, v1.1.3.11302
  TitanClassicPerformance, v1.1.3.11302
  TitanClassicReagentTracker, v1.13.2 (1.0.5)
  TitanClassicRegen, v1.1.3.11302
  TitanClassicRepair, v1.1.3.11302
  TitanClassicVolume, v1.1.3.11302
  TitanClassicXP, v1.1.3.11302
  TitanProfessionsMulti, v1.3
  TitanReputations, vv1.1-classic
  TomCats, v0.0.2
  TomTom, vv11302-1.0.8
  UsedInRecipe, v1.1.0
  WeakAuras, v2.15.5
  XLoot, v8.1-1
  XLootGroup, v8.1-1
  XLootMaster, v8.1-1
  XLootMonitor, v8.1-1
  ZPerl, v5.8.7
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=bc9)
```

**Comment by IrcDirk** [comment] 2019-11-13 09:13
Sorry cant reproduce. Please provide which quest it was.

**Comment by IrcDirk** [comment] 2019-11-21 16:17
Closing no more info provided.

**Closed by IrcDirk** 2019-11-21 16:17 UTC
Labels: Need more info
