### ISSUE TITLE
I am unable to see a quest monsters on hover

### ISSUE THREAD

**Issue by azuma-sv** [IrcDirk/Carbonite-Classic#132] opened 2020-04-17 13:58 UTC
Hello @IrcDirk !
I am experiencing a small problem with Carbonite.
I have a quest Worgens in the forest (Part 1) and alaso I can see a correct location of this monster on the map. But when I hover over this monster - I can't see that this mob is correct one.
![image](https://user-images.githubusercontent.com/13999928/79576764-743c1600-80cc-11ea-982d-5cf66adb74dc.png)

Can you please help me to fix this problem?
ps. It's not only for this quest. This feature is just disabled for me somehow. And I can't find any setting for it.
Thanks!

**Comment by IrcDirk** [comment] 2020-04-17 14:04
This is duplicate of issue #22. This is not implemented. For now just use Questie addon.

**Closed** 2020-05-09 08:31 UTC
Labels: Duplicate
