### ISSUE TITLE
my level 60 character is generating about 10 lua errors per second while in borean tundra

### ISSUE THREAD

**Issue by 5l4y3r-burrito** [IrcDirk/Carbonite-Classic#270] opened 2022-10-24 07:48 UTC
Message: Interface\AddOns\Carbonite\NxTravel.lua:389: attempt to index local 'dstInfo' (a nil value)
Time: Mon Oct 24 02:47:25 2022
Count: 570
Stack: Interface\AddOns\Carbonite\NxTravel.lua:389: attempt to index local 'dstInfo' (a nil value)

Locals:

**Comment by 5l4y3r-burrito** [comment] 2022-10-24 07:49
Message: Interface\AddOns\Carbonite\NxTravel.lua:389: attempt to index local 'dstInfo' (a nil value)
Time: Mon Oct 24 02:46:29 2022
Count: 1
Stack: Interface\AddOns\Carbonite\NxTravel.lua:389: attempt to index local 'dstInfo' (a nil value)
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:10536: in function `TrackOnMap'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:10334: in function `CalcAutoTrack'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:9210: in function `UpdateList'
[string "@Interface\AddOns\Carbonite.Quests\NxQuest.lua"]:9123: in function `func'
[string "@Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10602
 DailyTypes = <table> {
 }
 AcceptPool = <table> {
 }
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3244
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3298
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11237
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5257
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11499
 SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4332
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11647
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3182
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5071
 Custom = <table> {
 }
 TTChange = <table> {
 }
 OldMap = 0
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10881
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3484
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4308
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4116
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4031
 GetQuestObjectiveInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4274
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4795
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5342
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3352
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10593
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5889
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10652
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11492
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4008
 GetQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11629
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8341
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4256
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4159
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3432
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8286
 OnProfileChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2158
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4902
 CreateLink = <function> defined @Interface\AddOns\Car

**Comment by 5l4y3r-burrito** [comment] 2022-10-24 07:50
these errors stop when i toggle off Auto Track (purple circle button at the top of quest tracker)

**Comment by IrcDirk** [comment] 2022-10-24 10:22
Thanks for the report, ill check it as soon as i get to Borean ;)

**Comment by IrcDirk** [comment] 2022-11-08 07:35
Seems everything is fine on my side. Borean Tundra => Barov Family Fortune no auto tracking issues.

**Comment by IrcDirk** [comment] 2022-11-09 19:45
Closing since i cant reproduce and author of this issue doesnt respond.

**Closed by IrcDirk** 2022-11-09 19:45 UTC
