### ISSUE TITLE
Quest watch window is double windowed and only 1 can be adjusted ( the useless one)

### ISSUE THREAD

**Issue by Leonardpana01** [IrcDirk/Carbonite-Classic#264] opened 2022-10-08 19:50 UTC
On the quest watch window when you want to freely adjust the size is just adjusting a darker window on the background but the actual quest watch window shows the same with couple of quests in it that always changes the number (sometimes shows 2 quests and I have to scroll long way to the 10th quest for example by showing the last two , 9th and 10th) and has a scroll bar on it. What I want to have is freely adjustable window that as big as you make it more quests shows in it. For example if I have 10 quests, and i want to see all of them in same time I want to make the window bigger , but when I do that , the window gets bigger , right, but only the background and shows like 2-3 quests, or in this screen shot i managed to show 6 quests, but I don't know how as is always chaging the number and I have to scroll in order to see the last quest for example, will drop a screen shot to show you what I mean. I checked all the option and still seems buggy and dooesn't work.. In TBC classic was working perfectly fine. I will show 2 examples 1 how should be ( basically how was before in 3.3.4 and 1 how is now). and yes I selected the option in setting for fixed sized window on and off but I can't make it work like it was before . Thanks
![194700572-51de3c3d-eaab-4e07-a411-6a921e3d096c](https://user-images.githubusercontent.com/115345425/194725533-efe9c7c2-ef6a-4c8b-880d-2804c5711d1c.jpg)
![194700573-ecf1dbd7-64f7-4a03-9aa1-a91003de8394](https://user-images.githubusercontent.com/115345425/194725534-56b6811f-e354-44d1-8a7d-1baeebeb0e6a.jpg)

**Comment by IrcDirk** [comment] 2022-10-10 04:24
Cant reproduce everything works fine on my side. It might be another addon that causes that issue, try disabling all other addons leave only Carbonite + Modules enabled.

**Comment by Leonardpana01** [comment] 2022-10-11 23:41
yes, you are right , was questie that was making carbonite to do that, but I had questie just to be able to share the quests with my mates, as if I use carbonite for that just shares the text, not the clickable link to see details , am I doing something wrong there as well, or actually with Carbonite you basically can't share the quest links in order to be clicked by the people I share to to see details?

**Comment by IrcDirk** [comment] 2022-10-12 14:02
Thats another issue. Please dont mix those. Closing...

**Closed by IrcDirk** 2022-10-12 14:02 UTC

**Comment by Leonardpana01** [comment] 2022-10-12 14:03
nope, doesn't work , was a temporary fix looks like , now I even delete all my addons, I reset the settings in carbonite from courseforge, and I reinstalled the carbonite only and still the same thing is happening. only having carbonite in the addon folder... is just bugging me how well it works on the private warmane and how bad is working on the official server lol...

**Comment by Leonardpana01** [comment] 2022-10-12 14:05
is  not fixed same thing is happening

**Comment by Leonardpana01** [comment] 2022-10-12 14:07
is no other addon installed, i restarted the game and still having same issue, more now shows me only 1 quest, and I have the scroll bar on the side so small that I have to use it in order to see the other quests,,,

**Comment by Leonardpana01** [comment] 2022-10-12 14:10
i did that couple of times, and of course all the time i keep restarting the game and try again... I don't want to be a pain, but really doesn't work lol... let me submit another screen shot to show you

**Comment by IrcDirk** [comment] 2022-10-12 14:11
Works for me. If i cant reproduce then i cant fix it. U sure u are using latest version?

**Comment by Leonardpana01** [comment] 2022-10-12 14:13
I literally updated it around 1 hour ago
![bad](https://user-images.githubusercontent.com/115345425/195366688-e7749265-d646-4141-8411-9137b37992fc.PNG)

**Comment by Leonardpana01** [comment] 2022-10-12 14:15
if can't be fixed, and can't be reproduced... i don't know, maybe is just an enviromental issue, maybe I am that unlucky one... thanks for tryong though.. i might have ot live with it, or try to find something similar.. Thanks again

**Comment by IrcDirk** [comment] 2022-10-12 14:16
I tried to reproduce i just cant...

DID U TIRED WITH ONLY CARBONITE + MODULES ENABLED?

**Comment by Leonardpana01** [comment] 2022-10-12 14:23
Yes only carbonite and i saw its still doing it, I tried leave on quest and maps , and still ... so yes
![Uploading bad 2.PNG…]()

**Comment by IrcDirk** [comment] 2022-10-12 14:25
Try to delete all saved settings in WTF folder.

**Comment by Leonardpana01** [comment] 2022-10-12 14:30
I deleted the content in WTF folder , still , man, is fine, don't want to give u extra head aches for nothing as seems like nothing is changing, and if it works for others , that's it..

**Comment by Leonardpana01** [comment] 2022-10-12 14:31
I am ready to give up, so don't worry, thanks for trying

**Comment by IrcDirk** [comment] 2022-10-12 14:31
No one ever reported this issue :( Sorry seems its your WoW problem... really dont know what can it be.

**Comment by Leonardpana01** [comment] 2022-10-12 14:32
eh, it is what it is ... I will see . thanks again

**Comment by IrcDirk** [comment] 2022-10-12 14:40
Weird never seen such issues... and u are only one reporting it.

**Comment by IrcDirk** [comment] 2022-10-12 14:41
Try installing BugSack and BugGrabber maybe u are getting some errors but u dont see them.

**Comment by Leonardpana01** [comment] 2022-10-12 14:51
I did, no bugs yay! , that's what it says... really thank you very much for your support, well, things are a bit weird here, but no probs , will manage it. Have  a great one, cheers

**Comment by IrcDirk** [comment] 2022-10-12 15:04
Its the same code as it was in TBC... so nothing changed ;) Sorry that i cant help u more.
